apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    uid: maveretta-overview-live
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    jsonData:
      httpMethod: POST
      timeInterval: 5s
    version: 1
