global:
  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_from: 'your-email@gmail.com'
  smtp_auth_username: 'your-email@gmail.com'
  smtp_auth_password: 'your-app-password'

route:
  group_by: ['alertname', 'service']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'default-receiver'
  routes:
    - match:
        severity: critical
      receiver: 'critical-alerts'
      repeat_interval: 30m
    - match:
        severity: warning
      receiver: 'warning-alerts'

receivers:
  - name: 'default-receiver'
    email_configs:
      - to: 'your-email@gmail.com'
        text: |
          [Maveretta] Alert: {{ .GroupLabels.alertname }}
          
          Alert: {{ .GroupLabels.alertname }}
          Service: {{ .GroupLabels.service }}
          Severity: {{ .CommonLabels.severity }}

          Summary: {{ .CommonAnnotations.summary }}
          Description: {{ .CommonAnnotations.description }}

          Impact: {{ .CommonAnnotations.impact }}
          Action: {{ .CommonAnnotations.action }}

          Start time: {{ .StartsAt }}
          {{ if .GeneratorURL }}
          Details: {{ .GeneratorURL }}
          {{ end }}

  - name: 'critical-alerts'
    email_configs:
      - to: 'your-email@gmail.com'
        text: |
          🚨 CRITICAL - [Maveretta] {{ .GroupLabels.alertname }}
          
          🚨 CRITICAL ALERT - IMMEDIATE ACTION REQUIRED 🚨

          Alert: {{ .GroupLabels.alertname }}
          Service: {{ .GroupLabels.service }}
          Severity: {{ .CommonLabels.severity }}

          Summary: {{ .CommonAnnotations.summary }}
          Description: {{ .CommonAnnotations.description }}

          IMPACT: {{ .CommonAnnotations.impact }}
          ACTION REQUIRED: {{ .CommonAnnotations.action }}

          Start time: {{ .StartsAt }}
          {{ if .GeneratorURL }}
          Details: {{ .GeneratorURL }}
          {{ end }}

  - name: 'warning-alerts'
    email_configs:
      - to: 'your-email@gmail.com'
        text: |
          ⚠️ WARNING - [Maveretta] {{ .GroupLabels.alertname }}
          
          ⚠️ WARNING ALERT

          Alert: {{ .GroupLabels.alertname }}
          Service: {{ .GroupLabels.service }}
          Severity: {{ .CommonLabels.severity }}

          Summary: {{ .CommonAnnotations.summary }}
          Description: {{ .CommonAnnotations.description }}

          Impact: {{ .CommonAnnotations.impact }}
          Action: {{ .CommonAnnotations.action }}

          Start time: {{ .StartsAt }}
          {{ if .GeneratorURL }}
          Details: {{ .GeneratorURL }}
          {{ end }}

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'service']