apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    uid: prometheus-ds
    editable: false
    jsonData:
      httpMethod: POST
      timeInterval: 5s
